spring:
  cloud:
    discovery:
      enabled: true
    config:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8080/applications

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVER-SERVER-URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true


#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"